language: go

go:
  - 1.13.3
  - tip

before_install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo

install:
  - go get -t -v ./...

script:
  - go test ./parser -coverprofile=coverage.txt -covermode=atomic
  - golint -set_exit_status ./...
  - gocyclo -over 15 ./parser

after_success:
  - bash <(curl -s https://codecov.io/bash)